# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1650e3d0-e8bf-4286-a09b-164be15514e6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1650e3d0-e8bf-4286-a09b-164be15514e6".device = "/dev/disk/by-uuid/1650e3d0-e8bf-4286-a09b-164be15514e6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/544C-8EC8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-703ca976-49b0-47a1-9a57-f26bd20f6fe9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
